name: ci
on:
  pull_request:
  push: # This is only run when PRs are merged into master
    branches:
      - master
  workflow_dispatch:
jobs:
  validate_datafiles:
    name: ci_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build -L .#checks.x86_64-linux.pytest-facts
      - run: nix build -L .#checks.x86_64-linux.duplicates-facts
      - run: nix build -L .#checks.x86_64-linux.perl-switches
      - run: nix build -L .#checks.x86_64-linux.openwrt-golden
      - run: nix build -L .#checks.x86_64-linux.formatting
      - run: nix build -L .#scaleInventory
